markdown: kramdown
comments: true
highligher: pygments
safe: true
permalink: /posts/:title/
kramdown:
  input: GFM
  hard_wrap: false

url: http://simonjbeaumont.com
baseurl:

title: Skylight Symmetry
description: >
  Someone with nothing better to say writing for someone
  with nothing better to do. On software, music and life.
keywords: [beaumont, si, beaumont, blog, software, cambridge, ocaml, citrix]
author:
  name: Si Beaumont
  twitter: simonjbeaumont
  github: simonjbeaumont
  gravatar_hash: 879c21ada065dea971833062417b17cd
  descr: >-
    Blackpool-born & Cambridge-based.
    Full-time hacker & Part-time consumer of Dr. Pepper.
disqus: skylightsymmetry

featured_post: docker-dashboard

exclude: ["CNAME", "_config.yml"]
